- hosts: bastion
  tasks: 
  - name: install the 'Development tools' package group
    become: true
    yum:
      name: "@Development tools"
      state: present

  - name: install mariadb
    become: true
    yum: 
      name: 
        - mariadb-server
        - mariadb-devel
        - readline-devel 
        - perl-ExtUtils-MakeMaker.noarch 
        - pam-devel

- hosts: all
  tasks:
  - name: install munge
    become: true
    yum:
      name:
        - munge
        - munge-libs
        - munge-devel
  - name: create munge group
    become: true
    group:
      name: munge
      gid: 801
      state: present
      system: yes
  - name: create munge user
    become: true
    user: 
      name: munge
      comment: "MUNGE Uid 'N' Gid Emporium"
      uid: 801
      group: 801
      shell: /sbin/nologin
      home: /var/lib/munge
      state: present
  - name: Repository
    become: true
    yum_repository: 
      name: OCI-HPC
      description: OCI-HPC
      baseurl: https://objectstorage.us-ashburn-1.oraclecloud.com/n/hpc/b/rpms/o/
      gpgcheck: no

- hosts: bastion
  become: true
  tasks: 
  - name: install slurm server
    yum: 
      name: 
        - slurm
        - slurm-contribs
        - slurm-slurmctld
        - slurm-perlapi
        - slurm-devel 
        - slurm-slurmctld

- hosts: compute
  become: true
  tasks: 
  - name: install slurm server
    yum: 
      name: 
        - slurm-slurmd
        - slurm
        - slurm-contribs
        - slurm-slurmctld
        - slurm-perlapi
        - slurm-devel 

- hosts: bastion
  gather_facts: no
  tasks:
  - name: Create munge key
    become: true
    command: 
      cmd: create-munge-key
      creates: /etc/munge/munge.key

- hosts: localhost
  gather_facts: no
  connection: local
  become: true
  tasks: 
  - name: copy munge.key
    shell: 
      cmd: cp /etc/munge/munge.key /tmp/munge.key
      warn: false
  - name: set permissions 
    shell: 
      cmd: chown opc:opc /tmp/munge.key
      warn: false

- hosts: all
  gather_facts: no
  tasks: 
  - name: Copy munge key
    become: true
    copy:
      src: /tmp/munge.key
      dest: /etc/munge/munge.key
      owner: munge
      group: munge
      mode: '0400'

- hosts: all 
  gather_facts: no 
  tasks: 
  - file: 
      path: /tmp/munge.key
      state: absent

- hosts: all
  tasks: 
  - name: set /var/log/munge permissions
    become: true
    file: 
      path: /var/log/munge
      owner: munge
      group: munge
      mode: '0700'
  - name: set /etc/munge permissions
    become: true
    file: 
      path: /etc/munge
      owner: munge
      group: munge
  - name: set /run/munge permissions
    become: true
    file:
      path: /run/munge
      owner: munge
      group: munge
  
  - name: enable and start munge
    become: true
    service: 
      state: started
      name: munge
      enabled: yes

  - name: set /etc/slurm
    become: true
    file: 
      path: /etc/slurm
      owner: slurm
      group: slurm
      state: directory

  - name: set /var/spool/slurmd
    become: true
    file: 
      path: /var/spool/slurmd
      owner: slurm
      group: slurm
      state: directory

  - name: set /var/spool/slurm
    become: true
    file: 
      path: /var/spool/slurm
      owner: slurm
      group: slurm
      state: directory


- hosts: bastion
  become: true
  tasks: 
  - name: slurm_cfg
    become: true
    template:
      src: _slurm.j2
      dest: /etc/slurm/slurm.conf
      owner: slurm
      group: slurm
    register: slurm_config
    notify: slurm_restart
  - name: enable and start slurmctld
    become: true
    service: 
      state: started
      name: slurmctld
      enabled: yes
  handlers:
  - name: slurm_restart
    command: bash -c "systemctl restart slurmctld"
    when: slurm_config.changed


- hosts: compute
  become: true
  tasks: 
  - name: slurm_cfg
    become: true
    template:
      src: _slurm.j2
      dest: /etc/slurm/slurm.conf
      owner: slurm
      group: slurm
    register: slurm_config
    notify: slurm_restart
  - name: enable and start slurmd
    become: true
    service: 
      state: started
      name: slurmd
      enabled: yes
  handlers:
  - name: slurm_restart
    command: bash -c "systemctl restart slurmd"
    when: slurm_config.changed


