rdma_pci_ids:
  BM.GPU4.8:
    - "0000:48:00.0"
    - "0000:48:00.1"
    - "0000:4c:00.0"
    - "0000:4c:00.1"
    - "0000:0c:00.0"
    - "0000:0c:00.1"
    - "0000:16:00.0"
    - "0000:16:00.1"
    - "0000:c3:00.0"
    - "0000:c3:00.1"
    - "0000:d1:00.0"
    - "0000:d1:00.1"
    - "0000:8a:00.0"
    - "0000:8a:00.1"
    - "0000:94:00.0"
    - "0000:94:00.1"
  BM.HPC2.36:
    - "0000:5e:00.0"
  BM.Optimized3.36:
    - "0000:98:00.0"
